Repository zaidi-01/PantryPal, pull requests merged in 2023-11, with the labels that each got.

#35 feat(backend): implement fridge controller
  client/src/app/fridge/fridge.component.ts
  client/src/services/fridge/fridge.service.ts
  server/Controllers/FridgeController.cs
Labels: angular, .net

#38 feat: implement recipe view
  client/angular.json
  client/src/app/app.module.ts
  client/src/app/nav-menu/nav-menu.component.html
  client/src/app/recipe-list/recipe-list.component.html
  client/src/app/recipe/recipe.component.html
  client/src/app/recipe/recipe.component.scss
  client/src/app/recipe/recipe.component.ts
  server/Controllers/RecipeController.cs
Labels: angular, .net

#49 feat: add admin module and dashboard component
  client/src/admin/admin-dashboard/admin-dashboard.component.html
  client/src/admin/admin-dashboard/admin-dashboard.component.scss
  client/src/admin/admin-dashboard/admin-dashboard.component.spec.ts
  client/src/admin/admin-dashboard/admin-dashboard.component.ts
  client/src/admin/admin.module.ts
  client/src/api-authorization/api-authorization.module.ts
  client/src/api-authorization/authorize.guard.ts
  client/src/api-authorization/login-menu/login-menu.component.html
  client/src/api-authorization/login-menu/login-menu.component.scss
  client/src/api-authorization/login-menu/login-menu.component.spec.ts
  client/src/api-authorization/login-menu/login-menu.component.ts
  client/src/app/app.constants.ts
  client/src/app/app.module.ts
  client/src/app/home/home.component.spec.ts
  client/src/app/home/home.component.ts
  client/src/app/nav-menu/nav-menu.component.html
  client/src/app/nav-menu/nav-menu.component.ts
  client/src/app/recipe-list/recipe-list.component.html
  client/src/app/recipe-list/recipe-list.component.ts
Labels: angular

#52 refactor: handle duplicate recipe search queries
  client/src/app/recipe-search/recipe-search.component.ts
Labels: angular

#54 feat: add razor pages for admin login
  client/src/admin/admin.module.ts
  client/src/api-authorization/authorize.guard.ts
  server/Areas/Identity/Pages/Account/Login.cshtml
  server/Areas/Identity/Pages/Account/Login.cshtml.cs
  server/Areas/Identity/Pages/Account/_ViewImports.cshtml
  server/Areas/Identity/Pages/_ViewImports.cshtml
  server/Areas/Identity/Pages/_ViewStart.cshtml
  server/Pages/Shared/_Layout.cshtml
  server/Pages/Shared/_LoginPartial.cshtml
  server/Pages/Shared/_ValidationScriptsPartial.cshtml
  server/Pages/_ViewStart.cshtml
  server/Program.cs
  server/server.csproj
Labels: .net

#55 refactor: refactor fridge to use virtual scrolling
  client/src/app/app.module.ts
  client/src/app/fridge/fridge.component.html
  client/src/app/fridge/fridge.component.scss
  client/src/app/fridge/fridge.component.ts
Labels: angular

#61 ci: add node.js workflow
  .config/dotnet-tools.json
  .github/workflows/dotnet.yml
  .github/workflows/node.js.yml
Labels: ci/cd
