Repository zaidi-01/PantryPal, pull requests merged in 2023-12, with the labels that each got.

#59 fix: fix ingredients not visually being removed in Fridge
  client/src/app/fridge/fridge.component.ts
Labels: bug, angular

#65 fix: input handling in delete recipe component
  client/src/admin/recipe-id-input/recipe-id-input.component.html
  client/src/admin/recipe-id-input/recipe-id-input.component.ts
Labels: bug, angular

#67 refactor: recipe-details layout and styling
  client/angular.json
  client/src/app/app.module.ts
  client/src/enums/dietary-restriction.enum.ts
  client/src/enums/recipe-category.enum.ts
  client/src/index.html
  client/src/interfaces/recipe.interface.ts
  client/src/main.ts
  client/src/services/http-client/http-client.service.ts
  client/src/services/recipe/recipe.service.ts
  client/src/shared/recipe-attribute/recipe-attribute.component.html
  client/src/shared/recipe-attribute/recipe-attribute.component.scss
  client/src/shared/recipe-attribute/recipe-attribute.component.spec.ts
  client/src/shared/recipe-attribute/recipe-attribute.component.ts
  client/src/shared/recipe-details/recipe-details.component.html
  client/src/shared/recipe-details/recipe-details.component.scss
  client/src/shared/recipe-details/recipe-details.component.ts
  client/src/shared/shared.module.ts
  client/src/styles/_utilities.scss
  client/src/styles/styles.scss
  server/Enums/DietaryRestriction.cs
  server/Enums/RecipeCategory.cs
Labels: angular

#66 feat: add confirmation dialog before deletion
  client/src/admin/delete-recipe/delete-recipe.component.ts
  client/src/app/app.module.ts
  client/src/interfaces/dialog.interface.ts
  client/src/interfaces/index.ts
  client/src/services/dialog/dialog.component.html
  client/src/services/dialog/dialog.component.scss
  client/src/services/dialog/dialog.component.spec.ts
  client/src/services/dialog/dialog.component.ts
  client/src/services/dialog/dialog.service.spec.ts
  client/src/services/dialog/dialog.service.ts
  client/src/services/index.ts
Labels: enhancement, angular

#70 fix: search failing due to a null check
  server/Controllers/RecipeController.cs
Labels: bug, .net

#57 feat: add filter and sort component
  client/src/app/app.module.ts
  client/src/app/recipe-search/filter-and-sort/filter-and-sort.component.html
  client/src/app/recipe-search/filter-and-sort/filter-and-sort.component.scss
  client/src/app/recipe-search/filter-and-sort/filter-and-sort.component.spec.ts
  client/src/app/recipe-search/filter-and-sort/filter-and-sort.component.ts
  client/src/app/recipe-search/recipe-search.component.html
  client/src/app/recipe-search/recipe-search.component.ts
  client/src/services/recipe/recipe.service.ts
  server/Controllers/RecipeController.cs
Labels: angular, .net
